# site properties and page defaults
title: NEURECA
subtitle: 
description: Dr. Hyojin Park's Research Group
header: images/background.svg
footer: images/background.svg

# site social media and other links
links:
  email: h.park@bham.ac.uk
  orcid: 0000-0002-7527-8280
  google-scholar: Vyn8xRQAAAAJ
  linkedin: hyojin-park-neureca  
  youtube: neureca
  instagram: neureca_research
  github: hyojin-park-neuro
  twitter: HyojinParkNeuro
  x: HyojinParkNeuro
  

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
