- id: doi:10.1016/j.cub.2024.06.072
  type: paper
  date: 2024-7-23
  image: https://ars.els-cdn.com/content/image/1-s2.0-S096098222400856X-gr1.jpg
  tags:
    - speech-brain coupling
    - prosody
    - syntax
    - speech comprehension
    - delta
    - temporal response function
    - MEG/EEG

    
- id: doi:10.1016/j.cub.2024.06.072
  type: paper
  date: 2024-7-23
  image: https://ars.els-cdn.com/content/image/1-s2.0-S096098222400856X-gr1.jpg
  tags:
    - speech-brain coupling
    - prosody
    - syntax
    - speech comprehension
    - delta
    - temporal response function
    - MEG/EEG

    
- id: doi:10.1101/2024.02.25.581860
  type: paper
  date: 2024-2-27
  image: https://www.biorxiv.org/content/biorxiv/early/2024/02/27/2024.02.25.581860/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - audiovisual speech
    - alpha
    - theta
    - attentional inhibition
    - congruency
    - MEG/EEG


- id: doi:10.1101/2024.02.01.578181
  type: paper
  date: 2024-2-1
  image: https://www.biorxiv.org/content/biorxiv/early/2024/02/01/2024.02.01.578181/F2.large.jpg?width=800&height=600&carousel=1
  tags:
    - speech comprehension
    - delta
    - prosodic cues
    - encoding model
    - MEG/EEG


- id: doi:10.1038/s41433-023-02845-w
  type: paper
  date: 2024-1-18
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41433-023-02845-w/MediaObjects/41433_2023_2845_Fig1_HTML.png?as=webp
  tags:
    - mTBI
    - mild traumatic brain injury
    - traumatic brain injury
    - OCT
    - optical coherence tomography
    - eye


- id: doi:10.1162/jocn_a_02059
  type: paper
  date: 2024-1-1
  image: images/figures_papers/Haider_2024_JCoN_Fig1.png
  tags:
    - audiovisual speech
    - lip movement
    - face mask
    - speech features
    - multi-speaker
    - MEG/EEG


- id: doi:10.7554/eLife.89703
  type: paper
  date: 2023-9-18
  image: https://prod--epp.elifesciences.org/iiif/2/89703%2Fv1%2Fcontent%2F490770v1_fig1.tif/full/max/0/default.jpg
  tags:
    - audiovisual speech
    - semantic gist
    - topic
    - keywords
    - topic model
    - latent dirichlet allocation (LDA)
    - multi-speaker
    - natural language processing (NLP)
    - large language model (LLMs)
    - MEG/EEG


- id: doi:10.1101/2023.05.15.540818
  type: paper
  date: 2023-5-15
  image: https://www.biorxiv.org/content/biorxiv/early/2023/05/15/2023.05.15.540818/F3.large.jpg?width=800&height=600&carousel=1
  tags:
    - audiovisual speech
    - lip movement
    - face mask
    - speech features
    - multi-speaker
    - MEG/EEG


- id: doi:10.1101/2022.06.21.497061
  type: paper
  date: 2022-6-22
  image: https://www.biorxiv.org/content/biorxiv/early/2022/06/22/2022.06.21.497061/F3.large.jpg?width=800&height=600&carousel=1
  tags:
    - semantic gist
    - topic
    - keywords
    - audiovisual integration
    - delta
    - theta
    - information theory
    - MEG/EEG
    - DTI


- id: doi:10.1016/j.neuroimage.2022.119044
  type: paper
  date: 2022-5-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811922001732-gr1.jpg
  tags:
    - stimulus reconstruction
    - face mask
    - audiovisual speech
    - formants
    - speech envelope
    - MEG/EEG


- id: doi:10.1101/2022.05.05.490770
  type: paper
  date: 2022-5-5
  image: https://www.biorxiv.org/content/biorxiv/early/2022/05/05/2022.05.05.490770/F1/graphic-1.large.jpg?width=800&height=600&carousel=1
  tags:
    - audiovisual speech
    - semantic gist
    - topic
    - keywords
    - topic model
    - latent dirichlet allocation (LDA)
    - multi-speaker
    - natural language processing (NLP)
    - large language model (LLMs)
    - MEG/EEG


- id: doi:10.1016/j.crneur.2021.100014
  type: paper
  date: 2021-5-19
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2665945X21000103-gr4.jpg
  tags:
    - audiovisual speech
    - auditory detection
    - lip movement
    - theta 
    - phase
    - MEG/EEG


- id: doi:10.1371/journal.pbio.2006558
  type: paper
  date: 2018-8-6
  image: https://journals.plos.org/plosbiology/article/figure/image?size=large&id=10.1371/journal.pbio.2006558.g002
  tags:
    - audiovisual speech
    - integration
    - pSTG
    - motor cortex
    - representational interaction
    - information theory
    - mutual information
    - partial information decomposition
    - synergy
    - redundancy
    - MEG/EEG


- id: doi:10.1080/23273798.2018.1506589
  type: paper
  date: 2018-9-26
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/plcp21/2020/plcp21.v035.i06/23273798.2018.1506589/20210511/images/large/plcp_a_1506589_f0004_oc.jpeg
  tags:
    - speech
    - speech tracking
    - prediction
    - top-down
    - delta
    - theta
    - beta
    - MEG/EEG


- id: doi:10.1038/srep41592
  type: paper
  date: 2017-2-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fsrep41592/MediaObjects/41598_2017_Article_BFsrep41592_Fig3_HTML.jpg?as=webp
  tags:
    - long-term memory
    - memory encoding
    - alpha
    - gamma
    - cross-frequency
    - functional connectivity
    - graph filtration
    - persistent homology
    - MEG/EEG


- id: doi:10.1523/ENEURO.0334-16.2016
  type: paper
  date: 2017-1-16
  image: https://www.eneuro.org/content/eneuro/3/6/ENEURO.0334-16.2016/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - cross-frquency coupling
    - phase-amplitude coupling
    - spurious coupling
    - brain oscillations
    - MEG/EEG    


- id: doi:10.1038/srep28092
  type: paper
  date: 2016-6-16
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fsrep28092/MediaObjects/41598_2016_Article_BFsrep28092_Fig2_HTML.jpg?as=webp
  tags:
    - long-term memory
    - memory encoding
    - alpha
    - gamma
    - cross-frequency coupling
    - phase-amplitude coupling
    - MEG/EEG


- id: doi:10.7554/eLife.14521
  type: paper
  date: 2016-5-5
  image: https://iiif.elifesciences.org/lax/14521%2Felife-14521-fig2-v2.tif/full/,1500/0/default.jpg
  tags:
    - audiovisual speech
    - visual speech
    - speeck tracking
    - lip movement
    - speech intelligibility
    - coherence
    - MEG/EEG


- id: doi:10.1016/j.cub.2015.04.049
  type: paper
  date: 2015-6-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S096098221500500X-gr1.jpg
  tags:
    - speech tracking
    - top-down
    - auditory cortex
    - motor cortex
    - frontal cortex
    - information theory
    - transfer entropy
    - MEG/EEG


- id: doi:10.1002/hbm.22452
  type: paper
  date: 2014-2-12
  image: https://onlinelibrary.wiley.com/cms/asset/429827ab-1a27-4130-9fe0-df0e6f8d2cdb/hbm22452-fig-0003-m.jpg
  tags:
    - long-term memory
    - irrelevant memory
    - memory blocking
    - remember
    - no-remember
    - alpha
    - MEG/EEG    


- id: doi:10.1089/brain.2011.0046
  type: paper
  date: 2012-4-13
  image: images/paper_thumbnail_2012_brain_connect.jpg
  tags:
    - working memory
    - visuospatial memory
    - memory maintenance
    - cross-freuqnecy coupling
    - STG
    - brain oscillations
    - MEG/EEG       


- id: doi:10.1007/s00259-008-0808-z
  type: paper
  date: 2008-5-20
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00259-008-0808-z/MediaObjects/259_2008_808_Fig3_HTML.gif?as=webp
  tags:
    - resting state
    - default mode
    - glucose metabolism
    - interregional correlation
    - functional connectivity
    - metabolic connectivity
    - FDG-PET

