- id: doi:10.1101/2022.06.21.497061
  type: paper
  date: 2022-6-22
  image: images/photo.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1101/2022.06.21.497061
  tags:
    - semantic gist
    - audiovisual integration
    - delta
    - theta
    - information theory
    - MEG/EEG
    

- id: doi:10.1016/j.neuroimage.2022.119044
  type: paper
  date: 2022-5-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811922001732-gr1.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1016/j.neuroimage.2022.119044
  tags:
    - stimulus reconstruction
    - face masks
    - audiovisual speech
    - formants
    - speech envelope
    - MEG/EEG
    
   
- id: doi:10.1101/2022.05.05.490770
  type: paper
  date: 2022-5-5
  image: images/highlights_1.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1101/2022.05.05.490770
  tags:
    - audiovisual speech
    - semantic gist
    - topic model
    - multi-speaker
    - natural language processing (NLP)
    - large language model (LLMs)
    - MEG/EEG
   
   
- id: doi:10.7554/eLife.14521
  type: paper
  date: 2016-5-5
  image: https://iiif.elifesciences.org/lax/14521%2Felife-14521-fig2-v2.tif/full/,1500/0/default.jpg
  buttons:
    - type: website
      text: Website
      link:  https://doi.org/10.7554/eLife.14521
  tags:
    - audiovisual speech
    - visual speech
    - speeck tracking
    - lip movement
    - speech intelligibility
    - coherence
    - MEG/EEG
    
    
- id: doi:10.1016/j.cub.2015.04.049
  type: paper
  date: 2015-6-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S096098221500500X-gr1.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1016/j.cub.2015.04.049
  tags:
    - speech tracking
    - top-down
    - auditory cortex
    - motor cortex
    - transfer entropy
    - MEG/EEG
    
    
- id: doi:10.1002/hbm.22452
  type: paper
  date: 2014-2-12
  image: https://onlinelibrary.wiley.com/cms/asset/429827ab-1a27-4130-9fe0-df0e6f8d2cdb/hbm22452-fig-0003-m.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1002/hbm.22452
  tags:
    - memory
    - irrelevant memory
    - Remember
    - No-Remember
    - alpha
    - MEG/EEG    
    
    
- id: doi:10.1007/s00259-008-0808-z
  type: paper
  date: 2008-5-20
  image: images/photo.jpg
  buttons:
    - type: website
      text: Website
      link: https://doi.org/10.1007/s00259-008-0808-z
  tags:
    - resting state
    - default mode
    - interregional correlation
    - functional connectivity
    - metabolic connectivity
    - FDG-PET
