- id: doi:10.1101/2022.06.21.497061
  type: paper
  date: 2022-6-22
  image: images/cite_icon_arxiv_differential_roles.jpg
  tags:
    - semantic gist
    - audiovisual integration
    - delta
    - theta
    - information theory
    - MEG/EEG
    

- id: doi:10.1016/j.neuroimage.2022.119044
  type: paper
  date: 2022-5-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811922001732-gr1.jpg
  tags:
    - stimulus reconstruction
    - face masks
    - audiovisual speech
    - formants
    - speech envelope
    - MEG/EEG
    
   
- id: doi:10.1101/2022.05.05.490770
  type: paper
  date: 2022-5-5
  image: images/cite_icon_arxiv_get_the_gist.jpg
  tags:
    - audiovisual speech
    - semantic gist
    - topic
    - keyword
    - topic model
    - latent dirichlet allocation (LDA)
    - multi-speaker
    - natural language processing (NLP)
    - large language model (LLMs)
    - MEG/EEG


- id: doi:10.1016/j.crneur.2021.100014
  type: paper
  date: 2021-5-19
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2665945X21000103-gr1.jpg
  tags:
    - audiovisual speech
    - auditory detection
    - lip movement
    - theta 
    - phase
    - MEG/EEG
    

- id: doi:10.1371/journal.pbio.2006558
  type: paper
  date: 2018-8-6
  image: https://journals.plos.org/plosbiology/article/figure/image?size=large&id=10.1371/journal.pbio.2006558.g002
  tags:
    - audiovisual speech
    - integration
    - pSTG
    - motor cortex
    - representational interaction
    - information theory
    - partial information decomposition
    - synergy
    - redundancy
    - MEG/EEG
    
    
- id: doi:10.1080/23273798.2018.1506589
  type: paper
  date: 2018-9-26
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/plcp21/2020/plcp21.v035.i06/23273798.2018.1506589/20210511/images/large/plcp_a_1506589_f0004_oc.jpeg
  tags:
    - speech
    - speech tracking
    - prediction
    - top-down
    - delta
    - theta
    - beta
    - MEG/EEG
    
   
- id: doi:10.1038/srep41592
  type: paper
  date: 2017-2-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fsrep41592/MediaObjects/41598_2017_Article_BFsrep41592_Fig3_HTML.jpg?as=webp
  tags:
    - memory
    - memory encoding
    - alpha
    - gamma
    - cross-frequency
    - functional connectivity
    - graph filtration
    - persistent homology
    - MEG/EEG
    
    
- id: doi:10.1523/ENEURO.0334-16.2016
  type: paper
  date: 2017-1-16
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5237829/bin/enu0061622090003.jpg
  tags:
    - audiovisual speech
    - visual speech
    - speeck tracking
    - lip movement
    - speech intelligibility
    - coherence
    - MEG/EEG    


- id: doi:10.1038/srep28092
  type: paper
  date: 2016-6-16
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fsrep28092/MediaObjects/41598_2016_Article_BFsrep28092_Fig2_HTML.jpg?as=webp
  tags:
    - memory
    - memory encoding
    - alpha
    - gamma
    - cross-frequency coupling
    - phase-amplitude coupling
    - MEG/EEG
    
        
- id: doi:10.7554/eLife.14521
  type: paper
  date: 2016-5-5
  image: https://iiif.elifesciences.org/lax/14521%2Felife-14521-fig2-v2.tif/full/,1500/0/default.jpg
  tags:
    - audiovisual speech
    - visual speech
    - speeck tracking
    - lip movement
    - speech intelligibility
    - coherence
    - MEG/EEG
    
    
- id: doi:10.1016/j.cub.2015.04.049
  type: paper
  date: 2015-6-15
  image: https://ars.els-cdn.com/content/image/1-s2.0-S096098221500500X-gr1.jpg
  tags:
    - speech tracking
    - top-down
    - auditory cortex
    - motor cortex
    - transfer entropy
    - MEG/EEG
    
    
- id: doi:10.1002/hbm.22452
  type: paper
  date: 2014-2-12
  image: https://onlinelibrary.wiley.com/cms/asset/429827ab-1a27-4130-9fe0-df0e6f8d2cdb/hbm22452-fig-0003-m.jpg
  tags:
    - memory
    - irrelevant memory
    - remember
    - no-remember
    - alpha
    - MEG/EEG    
    
    
- id: doi:10.1089/brain.2011.0046
  type: paper
  date: 2012-4-13
  image: images/cite_icon_brain_connect_12.jpg
  tags:
    - working memory
    - visuospatial memory
    - memory maintenance
    - cross-freuqnecy coupling
    - STG
    - brain oscillations
    - MEG/EEG       
    
    
- id: doi:10.1007/s00259-008-0808-z
  type: paper
  date: 2008-5-20
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00259-008-0808-z/MediaObjects/259_2008_808_Fig3_HTML.gif?as=webp
  tags:
    - resting state
    - default mode
    - interregional correlation
    - functional connectivity
    - metabolic connectivity
    - FDG-PET


- id: 7ae2ecbc-e35f-429a-a30f-31812dfeb024
  title: Language Lateralization Using Magnetoencephalography (MEG): A Preliminary Study
  authors:
  - Seo-Young Lee
  - Eunjoo Kang
  - June Sic Kim
  - Sang-Kun Lee
  - Hyejin Kang
  - Hyojin Park
  - Sung Hun Kim
  - Seung Hwan Lee
  - Chun Kee Chung
  type: paper
  date: 2006-12-30
  publisher: Annals of Clinical Neurophysiology
  image: images/cite_icon_2006_language_lateralization.jpg
  link: https://koreascience.kr/article/JAKO200627362963917.page
  tags:
    - language
    - lateralzation
    - presurgical mapping
    - epilepsy
    - MEG/EEG
