- id: doi:10.1101/2022.06.21.497061
  type: paper
  date: 2022-6-22
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript Source
      link: https://doi.org/10.1101/2022.06.21.497061
  tags:
    - semantic gist
    - audiovisual integration
    - delta
    - theta
    - information theory
    

- id: doi:10.1016/j.neuroimage.2022.119044
  type: paper
  date: 2022-5-15
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript Source
      link: https://doi.org/10.1016/j.neuroimage.2022.119044
  tags:
    - stimulus reconstruction
    - face masks
    - audiovisual speech
    - formants
    - speech envelope
    

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
